services:
  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DATABASE: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_HOST: pg
    command: start-dev
    restart: always
    ports:
      - 8080:8080
    volumes:
      - keycloak-data:/opt/keycloak/data
    depends_on:
      - pg
    networks:
      - default

  pg:
    image: postgres:16.0
    restart: always
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - default

volumes:
  pg_data:
    driver: local
  keycloak-data:
    driver: local

networks:
  default:
    driver: bridge
